version: '3'
services:
  microservicejs:
    build:
      context: ./microservicejs
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./microservicejs:/app
    networks:
      - my-network

  microservicephp:
    build:
      context: ./microservicephp
      dockerfile: Dockerfile
    ports:
      - 8000:9000
    volumes:
      - ./microservicephp:/var/www/html
    networks:
      - my-network

  microservicepy:
    build:
      context: ./microservicepy
      dockerfile: Dockerfile
    ports:
      - 8082:5000
    volumes:
      - ./microservicepy:/app
    networks:
      - my-network

networks:
  my-network:
